#!/usr/bin/with-contenv bash


PUID=${PUID:-911}
PGID=${PGID:-911}

if [ ! "$(id -u mab)" -eq "$PUID" ]; then usermod -o -u "$PUID" mab ; fi
if [ ! "$(id -g mab)" -eq "$PGID" ]; then groupmod -o -g "$PGID" mab ; fi

echo "
 __.         .  .   .     ..
(__ ._  _.._.;_/|  .|_  _.|| __
.__)[_)(_][  | \|\_|[_)(_]||_)  *
    |            ._|
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u mab)
User gid:    $(id -g mab)
-------------------------------------
"
chown mab:mab /app
chown mab:mab /config
chown mab:mab /defaults
